-- Criação da tabela CATEGORIES
CREATE TABLE CATEGORIES (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL
);

-- Criação da tabela PRODUCTS
CREATE TABLE PRODUCTS (
  ID INTEGER NOT NULL PRIMARY KEY,
  NAME VARCHAR(100) NOT NULL,
  CATEGORY_ID INTEGER NOT NULL,
  PRICE NUMERIC(10, 2),
  QUANTITY INTEGER,
  FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORIES(ID)
);

-- Generator para CATEGORIES
CREATE GENERATOR GEN_CATEGORIES_ID;
SET GENERATOR GEN_CATEGORIES_ID TO 0;

-- Generator para PRODUCTS
CREATE GENERATOR GEN_PRODUCTS_ID;
SET GENERATOR GEN_PRODUCTS_ID TO 0;

-- Trigger para CATEGORIES
CREATE TRIGGER BI_CATEGORIES FOR CATEGORIES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_CATEGORIES_ID, 1);
END;

-- Trigger para PRODUCTS
CREATE TRIGGER BI_PRODUCTS FOR PRODUCTS
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
    NEW.ID = GEN_ID(GEN_PRODUCTS_ID, 1);
END;
